FROM ubuntu:18.04

ENV SDK_VERSION=sdk-tools-linux-3859397
WORKDIR /root

# Setup some deps
RUN export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get -y install nano unzip  wget curl libimobiledevice-utils libimobiledevice6 usbmuxd cmake git build-essential python openjdk-8-jdk

# Set JAVA_HOME
ENV JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/jre" \
    PATH=$PATH:$JAVA_HOME/bin

RUN apt update && apt install -y ffmpeg

# Install Android SDK
#=====================
ENV ANDROID_HOME=/root
ENV ANDROID_PLATFORM_VERSION="android-25"
ENV ANDROID_BUILD_TOOLS_VERSION=31.0.0

RUN wget -O tools.zip https://dl.google.com/android/repository/${SDK_VERSION}.zip && \
    unzip tools.zip && rm tools.zip && \
    chmod a+x -R $ANDROID_HOME && \
    chown -R root:root $ANDROID_HOME

ENV PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin

RUN mkdir -p ~/.android && \
    touch ~/.android/repositories.cfg && \
    echo y | sdkmanager "platform-tools" && \
    echo y | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS_VERSION" && \
    echo y | sdkmanager "platforms;$ANDROID_PLATFORM_VERSION"

ENV PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools

#Grab GADS-docker-cli from github and extract it in /usr/local/bin
RUN wget https://github.com/shamanec/GADS-docker-cli/releases/latest/download/docker-cli.zip
RUN unzip docker-cli.zip -d /usr/local/bin
RUN rm docker-cli.zip

# Setup nvm and install latest appium
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
RUN export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \
     . "$NVM_DIR/nvm.sh" && nvm install 14.17.6 && \
    nvm alias default 14.17.6 && \
    npm config set user 0 && npm config set unsafe-perm true && npm install -g appium

COPY configs/android-sync.sh /
COPY configs/nodeconfiggen-android.sh /opt/nodeconfiggen.sh
COPY configs/container-server /opt
ENTRYPOINT ["/bin/bash","-c","/android-sync.sh"]
